FROM ubuntu:18.04 AS stage-0

# Install build-essential etc
RUN set -x -e && \
    apt-get update && \
    apt-get install -y \
        build-essential \
        apt-utils \
        locales \
        curl \
        file \
        git \
        wget \
        tree \
        zip \
        man \
        sudo && \
    locale-gen en_US.UTF-8 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY etc/apt/apt.conf.d/01norecommend /etc/apt/apt.conf.d/01norecommend

# Create a user
ENV USER=dev
RUN set -x -e && \
    groupadd -g 999 docker && \
    useradd -G docker -m -s /bin/bash "$USER" && \
    echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER "$USER"
ENV HOME="/home/$USER"

# Install Linuxbrew
# https://github.com/Homebrew/brew/blob/master/docs/Linuxbrew.md
RUN set -x -e && \
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" && \
    eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv) && \
    brew --version && \
    brew update && \
    brew cleanup

ENV PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"

ENV HOMEBREW_NO_AUTO_UPDATE=1

# Install development packages
<%
brew_packages = [
  {name: "docker", base: "stage-0"},
  {name: "zsh", base: "stage-0"},
  {name: "zsh-syntax-highlighting", base: "stage-0"},
  {name: "vim", base: "stage-0"},
  {name: "peco", base: "stage-0"},
  {name: "go", base: "stage-0"},
  {name: "screen", base: "stage-0"},
  {name: "jq", base: "stage-0"},
  {name: "dep", base: "stage-0"},
  {name: "ctags", base: "stage-0"},
  {name: "python2", base: "stage-0"},
  {name: "node", base: "brew-python2"},
  {name: "dive", base: "brew-go"},
#  {name: "ghq", base: "brew-go"},
#  {name: "kubectl", base: "go"},
]
%>
<% brew_packages.each do |package| %>
FROM <%= package[:base] %> AS brew-<%= package[:name] %>
RUN set -x && brew install <%= package[:name] %>
RUN set -x && brew test <%= package[:name] %>
<% end %>

# Install go tools
FROM brew-go AS go-tools
ENV GOPATH="/go"
RUN set -x -e && \
    sudo mkdir "$GOPATH" && \
    sudo chown "$USER" "$GOPATH" && \
    export GOCACHE=/tmp && \
    go get github.com/nsf/gocode

FROM stage-0
<% brew_packages.each do |package| %>
COPY --from=brew-<%= package[:name] %> /home/linuxbrew/.linuxbrew/ /home/linuxbrew/.linuxbrew/
<% end %>
COPY --from=go-tools /go/ /go/
ENV PATH="/go/bin:$PATH"

# Set default environment variables
ENV EDITOR=vim
ENV GOPATH="$HOME"
ENV GHQ_ROOT="$HOME/src"
ENV LESSCHARSET=utf-8
