#!/usr/bin/env bash

set -e

exec docker run \
    --rm \
    -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /home/kazukisuda:/home/ksuda \
    -w /home/ksuda \
    superbrothers/dev \
    /bin/bash
