name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pull the image for faster build
      run: make pull
    - name: Build the image
      run: make build
    - name: Docker Login
      if: github.ref == 'refs/heads/master'
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the image
      if: github.ref == 'refs/heads/master'
      run: make push
