name: Upgrade brew packages
on:
  schedule:
  - cron: "0 0 1 * *" # Every month
  repository_dispatch: {}
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Homebrew
      run: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
        eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        brew --version
    - name: Update packages.txt
      run: |
         eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
         ./hack/update-packages.sh
         make Dockerfile
    - name: Create a Pull Request
      uses: peter-evans/create-pull-request@v1.1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        COMMIT_MESSAGE: Upgrade brew packages
        PULL_REQUEST_TITLE: Upgrade brew packages
