name: Upgrade brew packages
on:
  schedule:
  - cron: "0 0 * * 0" # Every week
  repository_dispatch: {}
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Homebrew
      run: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
        eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        brew --version
    - name: Update packages.txt
      run: |
         eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
         ./hack/update-packages.sh
         make Dockerfile
    - name: Create a Pull Request
      uses: peter-evans/create-pull-request@v2.4.4
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Upgrade brew packages
        title: Upgrade brew packages
        body: This PR upgrades brew packages.
        labels: automerge
